apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags: [{ key: 'task_id' }, { key: 'agent_id' }]
      serviceMap: { datasourceUid: prometheus }
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    uid: prometheus
